# Generated by Django 5.2.12 on 2026-06-20 07:46

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f07d1005-5bd7-4a09-8932-89765fa602d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f07d1005-5bd7-4a09-8932-89765fa602d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='viewers',
            field=models.ManyToManyField(related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
