# Generated by Django 5.2.12 on 2026-06-20 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categorymodel_id_alter_postmodel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('799427dc-8001-4fcc-8c76-6fa8db5bc127'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('799427dc-8001-4fcc-8c76-6fa8db5bc127'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('799427dc-8001-4fcc-8c76-6fa8db5bc127'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.postmodel')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
        ),
    ]
