# Generated by Django 5.2.12 on 2026-06-20 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postmodel_is_active_alter_categorymodel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d91872-6609-411a-aa7d-269979b58470'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d91872-6609-411a-aa7d-269979b58470'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d91872-6609-411a-aa7d-269979b58470'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
